
VersionFromEXE = \
	Source/Tools/VersionFromEXE/Properties/AssemblyInfo.cs \
	Source/Tools/VersionFromEXE/Program.cs \
	Source/Tools/VersionFromSVN/Properties/AssemblyInfo.cs \
	Source/Tools/VersionFromSVN/Program.cs

ChangelogMaker = \
	Source/Tools/ChangelogMaker/Properties/AssemblyInfo.cs \
	Source/Tools/ChangelogMaker/Program.cs \

Updater = \
	Source/Tools/Updater/UpdateBlockedForm.Designer.cs \
	Source/Tools/Updater/Properties/AssemblyInfo.cs \
	Source/Tools/Updater/Properties/Resources.Designer.cs \
	Source/Tools/Updater/MainForm.Designer.cs \
	Source/Tools/Updater/Program.cs \
	Source/Tools/Updater/Helpers/EmbeddedAssembly.cs \
	Source/Tools/Updater/Helpers/Webdata.cs \
	Source/Tools/Updater/Helpers/TaskbarProgress.cs \
	Source/Tools/Updater/MainForm.cs \
	Source/Tools/Updater/UpdateBlockedForm.cs

ColorPicker = \
	Source/Plugins/ColorPicker/Properties/AssemblyInfo.cs \
	Source/Plugins/ColorPicker/Properties/Resources.Designer.cs \
	Source/Plugins/ColorPicker/ColorWheel.cs \
	Source/Plugins/ColorPicker/Controls/ColorPickerSliderEventArgs.cs \
	Source/Plugins/ColorPicker/Controls/ColorPickerSlider.Designer.cs \
	Source/Plugins/ColorPicker/Controls/ColorPickerControl.cs \
	Source/Plugins/ColorPicker/Controls/ColorPickerSlider.cs \
	Source/Plugins/ColorPicker/Controls/ColorPickerControl.designer.cs \
	Source/Plugins/ColorPicker/ColorHandler.cs \
	Source/Plugins/ColorPicker/ColorChangedEventArgs.cs \
	Source/Plugins/ColorPicker/IColorPicker.cs \
	Source/Plugins/ColorPicker/BuilderPlug.cs \
	Source/Plugins/ColorPicker/Windows/SectorColorPicker.cs \
	Source/Plugins/ColorPicker/Windows/SectorColorPicker.Designer.cs \
	Source/Plugins/ColorPicker/Windows/LightColorPicker.cs \
	Source/Plugins/ColorPicker/Windows/ToolForm.Designer.cs \
	Source/Plugins/ColorPicker/Windows/LightColorPicker.Designer.cs \
	Source/Plugins/ColorPicker/Windows/ToolForm.cs \
	Source/Plugins/ColorPicker/ColorPickerType.cs

BuilderEffects = \
	Source/Plugins/BuilderEffects/Properties/AssemblyInfo.cs \
	Source/Plugins/BuilderEffects/Properties/Resources.Designer.cs \
	Source/Plugins/BuilderEffects/Interface/JitterVerticesForm.cs \
	Source/Plugins/BuilderEffects/Interface/ObjImportSettingsForm.Designer.cs \
	Source/Plugins/BuilderEffects/Interface/JitterVerticesForm.Designer.cs \
	Source/Plugins/BuilderEffects/Interface/JitterSectorsForm.Designer.cs \
	Source/Plugins/BuilderEffects/Interface/MenusForm.cs \
	Source/Plugins/BuilderEffects/Interface/DirectionalShadingForm.cs \
	Source/Plugins/BuilderEffects/Interface/JitterThingsForm.Designer.cs \
	Source/Plugins/BuilderEffects/Interface/JitterThingsForm.cs \
	Source/Plugins/BuilderEffects/Interface/MenusForm.Designer.cs \
	Source/Plugins/BuilderEffects/Interface/DirectionalShadingForm.designer.cs \
	Source/Plugins/BuilderEffects/Interface/ObjImportSettingsForm.cs \
	Source/Plugins/BuilderEffects/Interface/JitterSectorsForm.cs \
	Source/Plugins/BuilderEffects/Controls/BoolControl.cs \
	Source/Plugins/BuilderEffects/Controls/IntControl.cs \
	Source/Plugins/BuilderEffects/Controls/NumericUpDownEx.cs \
	Source/Plugins/BuilderEffects/Controls/IntControl.designer.cs \
	Source/Plugins/BuilderEffects/Controls/BoolControl.designer.cs \
	Source/Plugins/BuilderEffects/BuilderPlug.cs \
	Source/Plugins/BuilderEffects/Modes/ImportObjAsTerrainMode.cs

CommentsPanel = \
	Source/Plugins/CommentsPanel/Properties/AssemblyInfo.cs \
	Source/Plugins/CommentsPanel/Properties/Resources.Designer.cs \
	Source/Plugins/CommentsPanel/CommentInfo.cs \
	Source/Plugins/CommentsPanel/CommentsDocker.Designer.cs \
	Source/Plugins/CommentsPanel/CommentsDocker.cs \
	Source/Plugins/CommentsPanel/BuilderPlug.cs \
	Source/Plugins/CommentsPanel/CommentObjectType.cs

WadAuthorMode = \
	Source/Plugins/WadAuthorMode/Properties/AssemblyInfo.cs \
	Source/Plugins/WadAuthorMode/Properties/Resources.Designer.cs \
	Source/Plugins/WadAuthorMode/WAuthorTools.cs \
	Source/Plugins/WadAuthorMode/WAuthorTools.Designer.cs \
	Source/Plugins/WadAuthorMode/WAuthorMode.cs \
	Source/Plugins/WadAuthorMode/BuilderPlug.cs

NodesViewer = \
	Source/Plugins/NodesViewer/Properties/AssemblyInfo.cs \
	Source/Plugins/NodesViewer/Properties/Resources.Designer.cs \
	Source/Plugins/NodesViewer/Split.cs \
	Source/Plugins/NodesViewer/Subsector.cs \
	Source/Plugins/NodesViewer/NodesForm.Designer.cs \
	Source/Plugins/NodesViewer/Seg.cs \
	Source/Plugins/NodesViewer/NodesForm.cs \
	Source/Plugins/NodesViewer/Node.cs \
	Source/Plugins/NodesViewer/BuilderPlug.cs \
	Source/Plugins/NodesViewer/NodesViewerMode.cs

USDF = \
	Source/Plugins/USDF/Properties/AssemblyInfo.cs \
	Source/Plugins/USDF/Properties/Resources.Designer.cs \
	Source/Plugins/USDF/MainForm.Designer.cs \
	Source/Plugins/USDF/ToolsForm.cs \
	Source/Plugins/USDF/BuilderPlug.cs \
	Source/Plugins/USDF/MainForm.cs \
	Source/Plugins/USDF/ToolsForm.Designer.cs

ImageDrawingExample = \
	Source/Plugins/ImageDrawingExample/ImageExampleMode.cs \
	Source/Plugins/ImageDrawingExample/Properties/AssemblyInfo.cs \
	Source/Plugins/ImageDrawingExample/BuilderPlug.cs

AutomapMode = \
	Source/Plugins/AutomapMode/Properties/AssemblyInfo.cs \
	Source/Plugins/AutomapMode/Properties/Resources.Designer.cs \
	Source/Plugins/AutomapMode/Interface/MenusForm.cs \
	Source/Plugins/AutomapMode/Interface/MenusForm.Designer.cs \
	Source/Plugins/AutomapMode/BuilderPlug.cs \
	Source/Plugins/AutomapMode/AutomapMode.cs

VisplaneExplorer = \
	Source/Plugins/VisplaneExplorer/Properties/AssemblyInfo.cs \
	Source/Plugins/VisplaneExplorer/Properties/Resources.Designer.cs \
	Source/Plugins/VisplaneExplorer/Tile.cs \
	Source/Plugins/VisplaneExplorer/Palette.cs \
	Source/Plugins/VisplaneExplorer/InterfaceForm.cs \
	Source/Plugins/VisplaneExplorer/NearestLineBlockmap.cs \
	Source/Plugins/VisplaneExplorer/VisplaneExplorerMode.cs \
	Source/Plugins/VisplaneExplorer/TilePoint.cs \
	Source/Plugins/VisplaneExplorer/PointResult.cs \
	Source/Plugins/VisplaneExplorer/InterfaceForm.Designer.cs \
	Source/Plugins/VisplaneExplorer/VPOManager.cs \
	Source/Plugins/VisplaneExplorer/BuilderPlug.cs \
	Source/Plugins/VisplaneExplorer/PointData.cs \
	Source/Plugins/VisplaneExplorer/ViewStats.cs

StairSectorBuilder = \
	Source/Plugins/StairSectorBuilder/Properties/AssemblyInfo.cs \
	Source/Plugins/StairSectorBuilder/Properties/Resources.Designer.cs \
	Source/Plugins/StairSectorBuilder/StairSectorBuilderMode.cs \
	Source/Plugins/StairSectorBuilder/BuilderPlug.cs \
	Source/Plugins/StairSectorBuilder/StairSectorBuilderForm.cs \
	Source/Plugins/StairSectorBuilder/StairSectorBuilderForm.designer.cs

TagRange = \
	Source/Plugins/TagRange/TagRangeForm.Designer.cs \
	Source/Plugins/TagRange/Properties/AssemblyInfo.cs \
	Source/Plugins/TagRange/Properties/Resources.Designer.cs \
	Source/Plugins/TagRange/ToolsForm.cs \
	Source/Plugins/TagRange/BuilderPlug.cs \
	Source/Plugins/TagRange/ToolsForm.Designer.cs \
	Source/Plugins/TagRange/TagRangeForm.cs

SoundPropagationMode = \
	Source/Plugins/SoundPropagationMode/Properties/AssemblyInfo.cs \
	Source/Plugins/SoundPropagationMode/Properties/Resources.Designer.cs \
	Source/Plugins/SoundPropagationMode/Interface/SoundEnvironmentPanel.cs \
	Source/Plugins/SoundPropagationMode/Interface/SoundEnvironmentPanel.Designer.cs \
	Source/Plugins/SoundPropagationMode/SoundEnvironmentMode.cs \
	Source/Plugins/SoundPropagationMode/SoundEnvironment.cs \
	Source/Plugins/SoundPropagationMode/SoundPropagationMode.cs \
	Source/Plugins/SoundPropagationMode/SoundPropagationDomain.cs \
	Source/Plugins/SoundPropagationMode/BuilderPlug.cs \
	Source/Plugins/SoundPropagationMode/Windows/MenusForm.designer.cs \
	Source/Plugins/SoundPropagationMode/Windows/ColorConfiguration.cs \
	Source/Plugins/SoundPropagationMode/Windows/ReverbsPickerForm.cs \
	Source/Plugins/SoundPropagationMode/Windows/ColorConfiguration.designer.cs \
	Source/Plugins/SoundPropagationMode/Windows/ReverbsPickerForm.Designer.cs \
	Source/Plugins/SoundPropagationMode/Windows/MenusForm.cs

TagExplorer = \
	Source/Plugins/TagExplorer/Properties/AssemblyInfo.cs \
	Source/Plugins/TagExplorer/Properties/Resources.Designer.cs \
	Source/Plugins/TagExplorer/Controls/TagExplorer.cs \
	Source/Plugins/TagExplorer/Controls/TagExplorer.Designer.cs \
	Source/Plugins/TagExplorer/BuilderPlug.cs \
	Source/Plugins/TagExplorer/NodeInfo.cs

BuilderModes = \
	Source/Plugins/BuilderModes/Properties/AssemblyInfo.cs \
	Source/Plugins/BuilderModes/Properties/Resources.Designer.cs \
	Source/Plugins/BuilderModes/Interface/WavefrontSettingsForm.cs \
	Source/Plugins/BuilderModes/Interface/DrawCurveOptionsPanel.cs \
	Source/Plugins/BuilderModes/Interface/UndoRedoPanel.Designer.cs \
	Source/Plugins/BuilderModes/Interface/ErrorCheckForm.Designer.cs \
	Source/Plugins/BuilderModes/Interface/SelectSimilarElementOptionsPanel.cs \
	Source/Plugins/BuilderModes/Interface/DrawCurveOptionsPanel.Designer.cs \
	Source/Plugins/BuilderModes/Interface/PastePropertiesOptionsForm.cs \
	Source/Plugins/BuilderModes/Interface/BridgeModeForm.cs \
	Source/Plugins/BuilderModes/Interface/FitTexturesForm.Designer.cs \
	Source/Plugins/BuilderModes/Interface/BridgeModeForm.Designer.cs \
	Source/Plugins/BuilderModes/Interface/PastePropertiesOptionsForm.Designer.cs \
	Source/Plugins/BuilderModes/Interface/DrawGridOptionsPanel.cs \
	Source/Plugins/BuilderModes/Interface/PreferencesForm.Designer.cs \
	Source/Plugins/BuilderModes/Interface/EditSelectionPanel.cs \
	Source/Plugins/BuilderModes/Interface/DrawLineOptionsPanel.Designer.cs \
	Source/Plugins/BuilderModes/Interface/FilterSelectedThingsForm.Designer.cs \
	Source/Plugins/BuilderModes/Interface/FindReplaceForm.cs \
	Source/Plugins/BuilderModes/Interface/SectorDrawingOptionsPanel.Designer.cs \
	Source/Plugins/BuilderModes/Interface/WavefrontSettingsForm.Designer.cs \
	Source/Plugins/BuilderModes/Interface/FilterSelectedThingsForm.cs \
	Source/Plugins/BuilderModes/Interface/FitTexturesForm.cs \
	Source/Plugins/BuilderModes/Interface/UndoRedoPanel.cs \
	Source/Plugins/BuilderModes/Interface/FindReplaceForm.Designer.cs \
	Source/Plugins/BuilderModes/Interface/CurveLinedefsOptionsPanel.cs \
	Source/Plugins/BuilderModes/Interface/CurveLinedefsOptionsPanel.Designer.cs \
	Source/Plugins/BuilderModes/Interface/DrawRectangleOptionsPanel.Designer.cs \
	Source/Plugins/BuilderModes/Interface/MenusForm.cs \
	Source/Plugins/BuilderModes/Interface/DrawGridOptionsPanel.Designer.cs \
	Source/Plugins/BuilderModes/Interface/DrawRectangleOptionsPanel.cs \
	Source/Plugins/BuilderModes/Interface/DrawEllipseOptionsPanel.cs \
	Source/Plugins/BuilderModes/Interface/PreferencesForm.cs \
	Source/Plugins/BuilderModes/Interface/MenusForm.Designer.cs \
	Source/Plugins/BuilderModes/Interface/MakeDoorForm.Designer.cs \
	Source/Plugins/BuilderModes/Interface/ErrorCheckForm.cs \
	Source/Plugins/BuilderModes/Interface/DrawLineOptionsPanel.cs \
	Source/Plugins/BuilderModes/Interface/SelectSimilarElementOptionsPanel.Designer.cs \
	Source/Plugins/BuilderModes/Interface/DrawEllipseOptionsPanel.Designer.cs \
	Source/Plugins/BuilderModes/Interface/SectorDrawingOptionsPanel.cs \
	Source/Plugins/BuilderModes/Interface/ObjExporterSettingsForm.cs \
	Source/Plugins/BuilderModes/Interface/ObjExporterSettingsForm.Designer.cs \
	Source/Plugins/BuilderModes/Interface/EditSelectionPanel.Designer.cs \
	Source/Plugins/BuilderModes/Interface/MakeDoorForm.cs \
	Source/Plugins/BuilderModes/IO/WavefrontExporter.cs \
	Source/Plugins/BuilderModes/VisualModes/BaseVisualMode.cs \
	Source/Plugins/BuilderModes/VisualModes/VisualMiddleDouble.cs \
	Source/Plugins/BuilderModes/VisualModes/EffectBrightnessLevel.cs \
	Source/Plugins/BuilderModes/VisualModes/VisualUpper.cs \
	Source/Plugins/BuilderModes/VisualModes/VisualCeiling.cs \
	Source/Plugins/BuilderModes/VisualModes/SectorLevelComparer.cs \
	Source/Plugins/BuilderModes/VisualModes/SectorData.cs \
	Source/Plugins/BuilderModes/VisualModes/Effect3DFloor.cs \
	Source/Plugins/BuilderModes/VisualModes/SectorLevel.cs \
	Source/Plugins/BuilderModes/VisualModes/NullVisualEventReceiver.cs \
	Source/Plugins/BuilderModes/VisualModes/SectorLevelType.cs \
	Source/Plugins/BuilderModes/VisualModes/VisualSidedefParts.cs \
	Source/Plugins/BuilderModes/VisualModes/EffectLineSlope.cs \
	Source/Plugins/BuilderModes/VisualModes/VisualMiddle3D.cs \
	Source/Plugins/BuilderModes/VisualModes/EffectGlowingFlat.cs \
	Source/Plugins/BuilderModes/VisualModes/EffectThingLineSlope.cs \
	Source/Plugins/BuilderModes/VisualModes/BaseVisualGeometrySidedef.cs \
	Source/Plugins/BuilderModes/VisualModes/VisualFloor.cs \
	Source/Plugins/BuilderModes/VisualModes/VisualLower.cs \
	Source/Plugins/BuilderModes/VisualModes/VisualFogBoundary.cs \
	Source/Plugins/BuilderModes/VisualModes/EffectCopySlope.cs \
	Source/Plugins/BuilderModes/VisualModes/ThingData.cs \
	Source/Plugins/BuilderModes/VisualModes/WallPolygon.cs \
	Source/Plugins/BuilderModes/VisualModes/BaseVisualSector.cs \
	Source/Plugins/BuilderModes/VisualModes/BaseVisualVertex.cs \
	Source/Plugins/BuilderModes/VisualModes/VisualActionResult.cs \
	Source/Plugins/BuilderModes/VisualModes/BaseVisualThing.cs \
	Source/Plugins/BuilderModes/VisualModes/EffectTransferFloorBrightness.cs \
	Source/Plugins/BuilderModes/VisualModes/IVisualEventReceiver.cs \
	Source/Plugins/BuilderModes/VisualModes/EffectPlaneCopySlope.cs \
	Source/Plugins/BuilderModes/VisualModes/VisualMiddleBack.cs \
	Source/Plugins/BuilderModes/VisualModes/BaseVisualGeometrySector.cs \
	Source/Plugins/BuilderModes/VisualModes/SectorEffect.cs \
	Source/Plugins/BuilderModes/VisualModes/EffectUDMFVertexOffset.cs \
	Source/Plugins/BuilderModes/VisualModes/VertexData.cs \
	Source/Plugins/BuilderModes/VisualModes/EffectThingVertexSlope.cs \
	Source/Plugins/BuilderModes/VisualModes/TexturePlane.cs \
	Source/Plugins/BuilderModes/VisualModes/EffectTransferCeilingBrightness.cs \
	Source/Plugins/BuilderModes/VisualModes/EffectThingSlope.cs \
	Source/Plugins/BuilderModes/VisualModes/VisualMiddleSingle.cs \
	Source/Plugins/BuilderModes/ClassicModes/DragVerticesMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/DragGeometryMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/DrawRectangleMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/EditSelectionMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/ErrorCheckMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/SectorsMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/FloorAlignMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/BlockMapMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/ThingsMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/FlatAlignMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/DrawGeometryMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/DragThingsMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/BaseClassicMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/CurveLinedefsMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/FindReplaceMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/DrawGridMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/DrawEllipseMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/VerticesMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/DragSectorsMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/LinedefsMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/DrawCurveMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/MakeSectorMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/BridgeMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/DragLinedefsMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/TriangulatorMode.cs \
	Source/Plugins/BuilderModes/ClassicModes/CeilingAlignMode.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultUnknownTexture.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckUnknownScripts.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultSectorInvalid.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultMissingTexture.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckUnknownFlats.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckMissingFlats.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultLineMissingFront.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultUnknownSectorEffect.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultUnknownThing.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckUnknownActions.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultSectorUnclosed.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckObsoleteThings.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultUnusedTexture.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultStuckThingInLine.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultStuckThingInThing.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultThingOutside.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultShortLinedef.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultObsoleteThing.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultUnknownThingAction.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckMissingActivations.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultLineOverlapping.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultMissingFlat.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultVertexOverlappingLine.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultOffGridVertex.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultUnknownLinedefAction.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultMissingActivation.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultUnknownFlat.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckUnknownTextures.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultUnknownLinedefScript.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultLineNotDoubleSided.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckLineReferences.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultLineMissingSides.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckClosedSectors.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultMapTooBig.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckOverlappingLines.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckUnusedThings.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ErrorResult.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckPolyobjects.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ErrorCheckerAttribute.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultVertexOverlappingVertex.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ErrorChecker.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckStuckThings.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultUnknownThingScript.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultUnusedThing.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckUnknownThings.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultInvalidPolyobjectThings.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultTexturesMisaligned.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckShortLinedefs.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckStrayVertices.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultNoErrors.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultLineNotSingleSided.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckUnusedTextures.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultStrayVertex.cs \
	Source/Plugins/BuilderModes/ErrorChecks/ResultInvalidPolyobjectLines.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckOffGridVertices.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckTextureAlignment.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckOverlappingVertices.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckMissingTextures.cs \
	Source/Plugins/BuilderModes/ErrorChecks/CheckMapSize.cs \
	Source/Plugins/BuilderModes/FindReplace/FindThingAction.cs \
	Source/Plugins/BuilderModes/FindReplace/FindSectorFloorHeight.cs \
	Source/Plugins/BuilderModes/FindReplace/FindLinedefFlags.cs \
	Source/Plugins/BuilderModes/FindReplace/FindSectorCeilingHeight.cs \
	Source/Plugins/BuilderModes/FindReplace/FindThingType.cs \
	Source/Plugins/BuilderModes/FindReplace/FindReplaceType.cs \
	Source/Plugins/BuilderModes/FindReplace/BaseFindSidedef.cs \
	Source/Plugins/BuilderModes/FindReplace/FindAnyTextureFlat.cs \
	Source/Plugins/BuilderModes/FindReplace/FindThingFlags.cs \
	Source/Plugins/BuilderModes/FindReplace/FindSectorFlat.cs \
	Source/Plugins/BuilderModes/FindReplace/FindSectorFlags.cs \
	Source/Plugins/BuilderModes/FindReplace/FindSectorCeilingFlat.cs \
	Source/Plugins/BuilderModes/FindReplace/FindThingThingRef.cs \
	Source/Plugins/BuilderModes/FindReplace/FindReplaceObject.cs \
	Source/Plugins/BuilderModes/FindReplace/FindLinedefThingRef.cs \
	Source/Plugins/BuilderModes/FindReplace/FindThingSectorRef.cs \
	Source/Plugins/BuilderModes/FindReplace/FindSidedefFlags.cs \
	Source/Plugins/BuilderModes/FindReplace/FindSidedefMiddleTexture.cs \
	Source/Plugins/BuilderModes/FindReplace/BaseFindSector.cs \
	Source/Plugins/BuilderModes/FindReplace/FindVertexNumber.cs \
	Source/Plugins/BuilderModes/FindReplace/BaseFindLinedef.cs \
	Source/Plugins/BuilderModes/FindReplace/FindReplaceAttribute.cs \
	Source/Plugins/BuilderModes/FindReplace/FindThingTag.cs \
	Source/Plugins/BuilderModes/FindReplace/FindSectorEffect.cs \
	Source/Plugins/BuilderModes/FindReplace/FindSectorFloorFlat.cs \
	Source/Plugins/BuilderModes/FindReplace/BaseFindThing.cs \
	Source/Plugins/BuilderModes/FindReplace/FindLinedefNumber.cs \
	Source/Plugins/BuilderModes/FindReplace/FindSidedefUpperTexture.cs \
	Source/Plugins/BuilderModes/FindReplace/FindSectorBrightness.cs \
	Source/Plugins/BuilderModes/FindReplace/FindSectorNumber.cs \
	Source/Plugins/BuilderModes/FindReplace/FindLinedefTypes.cs \
	Source/Plugins/BuilderModes/FindReplace/FindSidedefLowerTexture.cs \
	Source/Plugins/BuilderModes/FindReplace/FindSectorTags.cs \
	Source/Plugins/BuilderModes/FindReplace/FindThingAngle.cs \
	Source/Plugins/BuilderModes/FindReplace/FindSidedefNumber.cs \
	Source/Plugins/BuilderModes/FindReplace/FindThingNumber.cs \
	Source/Plugins/BuilderModes/FindReplace/FindSidedefTexture.cs \
	Source/Plugins/BuilderModes/FindReplace/FindLinedefSectorRef.cs \
	Source/Plugins/BuilderModes/FindReplace/FindLinedefTags.cs \
	Source/Plugins/BuilderModes/General/HintLabel.cs \
	Source/Plugins/BuilderModes/General/CopyStructures.cs \
	Source/Plugins/BuilderModes/General/BuilderModesTools.cs \
	Source/Plugins/BuilderModes/General/UndoGroup.cs \
	Source/Plugins/BuilderModes/General/LineLengthLabel.cs \
	Source/Plugins/BuilderModes/General/Association.cs \
	Source/Plugins/BuilderModes/General/BuilderPlug.cs \
	Source/Plugins/BuilderModes/General/SelectionLabel.cs
	
Core = \
	Source/Core/Editing/NullThingsFilter.cs \
	Source/Core/Editing/CustomThingsFilter.cs \
	Source/Core/Editing/CopyPasteManager.cs \
	Source/Core/Editing/EditModeInfo.cs \
	Source/Core/Editing/ClassicMode.cs \
	Source/Core/Editing/EditModeAttribute.cs \
	Source/Core/Editing/ThingsFilter.cs \
	Source/Core/Editing/UndoSnapshot.cs \
	Source/Core/Editing/EditMode.cs \
	Source/Core/Editing/EditingManager.cs \
	Source/Core/Editing/GridSetup.cs \
	Source/Core/Editing/UndoManager.cs \
	Source/Core/Properties/AssemblyInfo.cs \
	Source/Core/Properties/Settings.Designer.cs \
	Source/Core/Properties/Resources.Designer.cs \
	Source/Core/GZBuilder/md3/GZModel.cs \
	Source/Core/GZBuilder/md3/ModelReader.cs \
	Source/Core/GZBuilder/GZGeneral.cs \
	Source/Core/GZBuilder/Data/ScriptItem.cs \
	Source/Core/GZBuilder/Data/ThingCopyData.cs \
	Source/Core/GZBuilder/Data/LinedefColorPreset.cs \
	Source/Core/GZBuilder/Data/GlowingFlatData.cs \
	Source/Core/GZBuilder/Data/LinksCollector.cs \
	Source/Core/GZBuilder/Data/MapInfo.cs \
	Source/Core/GZBuilder/Data/ModelLoadState.cs \
	Source/Core/GZBuilder/Data/BoundingBox.cs \
	Source/Core/GZBuilder/Data/SkyboxInfo.cs \
	Source/Core/GZBuilder/Data/DynamicLight.cs \
	Source/Core/GZBuilder/Data/SharpCompressHelper.cs \
	Source/Core/GZBuilder/Data/EngineInfo.cs \
	Source/Core/GZBuilder/Data/ModelData.cs \
	Source/Core/Geometry/Angle2D.cs \
	Source/Core/Geometry/Plane.cs \
	Source/Core/Geometry/EarClipPolygon.cs \
	Source/Core/Geometry/LabelPositionInfo.cs \
	Source/Core/Geometry/Vector2D.cs \
	Source/Core/Geometry/ProjectedFrustum2D.cs \
	Source/Core/Geometry/Vector3D.cs \
	Source/Core/Geometry/Line3D.cs \
	Source/Core/Geometry/LinedefsTracePath.cs \
	Source/Core/Geometry/Tools.cs \
	Source/Core/Geometry/EarClipVertex.cs \
	Source/Core/Geometry/Triangulation.cs \
	Source/Core/Geometry/DrawnVertex.cs \
	Source/Core/Geometry/InterpolationTools.cs \
	Source/Core/Geometry/SidedefAngleSorter.cs \
	Source/Core/Geometry/SidedefsTracePath.cs \
	Source/Core/Geometry/CurveTools.cs \
	Source/Core/Geometry/LinedefSide.cs \
	Source/Core/Geometry/LinedefAngleSorter.cs \
	Source/Core/Geometry/Line2D.cs \
	Source/Core/Controls/Scripting/ScriptResourcesControl.designer.cs \
	Source/Core/Controls/Scripting/ScriptResourceDocumentTab.cs \
	Source/Core/Controls/Scripting/FindUsagesControl.Designer.cs \
	Source/Core/Controls/Scripting/ScriptResourcesControl.cs \
	Source/Core/Controls/Scripting/ScriptFileDocumentTab.cs \
	Source/Core/Controls/Scripting/FindUsagesControl.cs \
	Source/Core/Controls/Scripting/ScriptIconsManager.cs \
	Source/Core/Controls/Scripting/ScriptDocumentTab.cs \
	Source/Core/Controls/Scripting/ScriptLumpDocumentTab.cs \
	Source/Core/Controls/ScintillaConstants.cs \
	Source/Core/Controls/OptimizedListView.cs \
	Source/Core/Controls/ColorControl.cs \
	Source/Core/Controls/ColorFieldsControl.cs \
	Source/Core/Controls/SectorInfoPanel.Designer.cs \
	Source/Core/Controls/CheckboxArrayControl.Designer.cs \
	Source/Core/Controls/StatisticsControl.Designer.cs \
	Source/Core/Controls/CheckedColoredListBox.cs \
	Source/Core/Controls/ResourceListView.cs \
	Source/Core/Controls/ImageSelectorControl.cs \
	Source/Core/Controls/VisualStudioTabControl.cs \
	Source/Core/Controls/PairedFieldsControl.cs \
	Source/Core/Controls/TextureSelectorControl.cs \
	Source/Core/Controls/TagsSelector.Designer.cs \
	Source/Core/Controls/FieldsEditorControl.Designer.cs \
	Source/Core/Controls/PairedFloatControl.cs \
	Source/Core/Controls/ArgumentBox.Designer.cs \
	Source/Core/Controls/AngleControl.cs \
	Source/Core/Controls/ActionSpecialHelpButton.cs \
	Source/Core/Controls/ThingInfoPanel.Designer.cs \
	Source/Core/Controls/NumericTextbox.cs \
	Source/Core/Controls/ConfigurablePictureBox.cs \
	Source/Core/Controls/RenderTargetControl.cs \
	Source/Core/Controls/ThingBrowserControl.cs \
	Source/Core/Controls/SectorSlopeControl.cs \
	Source/Core/Controls/ImageBrowserControl.Designer.cs \
	Source/Core/Controls/ArgumentBox.cs \
	Source/Core/Controls/ColorControl.Designer.cs \
	Source/Core/Controls/TransparentLabel.cs \
	Source/Core/Controls/ToolStripNumericUpDown.cs \
	Source/Core/Controls/VertexInfoPanel.Designer.cs \
	Source/Core/Controls/FlatSelectorControl.cs \
	Source/Core/Controls/CollapsibleSplitContainer.cs \
	Source/Core/Controls/ActionSelectorControl.Designer.cs \
	Source/Core/Controls/ThingBrowserControl.Designer.cs \
	Source/Core/Controls/ImageBrowserCategoryItem.cs \
	Source/Core/Controls/StatisticsControl.cs \
	Source/Core/Controls/AutoSelectTextbox.cs \
	Source/Core/Controls/ThingInfoPanel.cs \
	Source/Core/Controls/ColorFieldsControl.Designer.cs \
	Source/Core/Controls/ButtonsNumericTextbox.Designer.cs \
	Source/Core/Controls/PasteOptionsControl.cs \
	Source/Core/Controls/VertexInfoPanel.cs \
	Source/Core/Controls/PairedIntControl.cs \
	Source/Core/Controls/PairedFieldsControl.Designer.cs \
	Source/Core/Controls/ToolStripCheckBox.cs \
	Source/Core/Controls/FieldsEditorControl.cs \
	Source/Core/Controls/FolderSelectDialog.cs \
	Source/Core/Controls/DebugConsole.designer.cs \
	Source/Core/Controls/DebugConsole.cs \
	Source/Core/Controls/LinedefInfoPanel.cs \
	Source/Core/Controls/FieldsEditorRow.cs \
	Source/Core/Controls/BufferedTreeView.cs \
	Source/Core/Controls/LinedefInfoPanel.Designer.cs \
	Source/Core/Controls/TagsSelector.cs \
	Source/Core/Controls/SectorInfoPanel.cs \
	Source/Core/Controls/TransparentPanel.cs \
	Source/Core/Controls/ResourceListEditor.Designer.cs \
	Source/Core/Controls/Docker.cs \
	Source/Core/Controls/ResourceListEditor.cs \
	Source/Core/Controls/ImageBrowserItem.cs \
	Source/Core/Controls/HintsPanel.cs \
	Source/Core/Controls/CommentEditor.cs \
	Source/Core/Controls/PairedIntControl.Designer.cs \
	Source/Core/Controls/ImageSelectorPanel.cs \
	Source/Core/Controls/ButtonsNumericTextbox.cs \
	Source/Core/Controls/ColoredComboBox.cs \
	Source/Core/Controls/ActionSelectorControl.cs \
	Source/Core/Controls/TransparentListView.cs \
	Source/Core/Controls/ActionSpecialHelpButton.Designer.cs \
	Source/Core/Controls/ArgumentsControl.Designer.cs \
	Source/Core/Controls/AngleControl.Designer.cs \
	Source/Core/Controls/TransparentTrackBar.cs \
	Source/Core/Controls/TagSelector.cs \
	Source/Core/Controls/DockersControl.cs \
	Source/Core/Controls/DockersTabsControl.cs \
	Source/Core/Controls/MultiSelectTreeview.cs \
	Source/Core/Controls/ImageBrowserControl.cs \
	Source/Core/Controls/HintsPanel.Designer.cs \
	Source/Core/Controls/PasteOptionsControl.Designer.cs \
	Source/Core/Controls/PairedFloatControl.Designer.cs \
	Source/Core/Controls/AngleControlEx.cs \
	Source/Core/Controls/DockersControl.Designer.cs \
	Source/Core/Controls/CheckboxArrayControl.cs \
	Source/Core/Controls/CommentEditor.Designer.cs \
	Source/Core/Controls/AngleControlEx.Designer.cs \
	Source/Core/Controls/TagSelector.Designer.cs \
	Source/Core/Controls/ImageSelectorControl.Designer.cs \
	Source/Core/Controls/SectorSlopeControl.Designer.cs \
	Source/Core/Controls/ButtonsNumericTextboxDesigner.cs \
	Source/Core/Controls/ArgumentsControl.cs \
	Source/Core/Plugins/Plug.cs \
	Source/Core/Plugins/Plugin.cs \
	Source/Core/Plugins/PluginManager.cs \
	Source/Core/Map/Thing.cs \
	Source/Core/Map/UniFields.cs \
	Source/Core/Map/Vertex.cs \
	Source/Core/Map/SelectionType.cs \
	Source/Core/Map/MapElement.cs \
	Source/Core/Map/SelectableElement.cs \
	Source/Core/Map/Sidedef.cs \
	Source/Core/Map/MapSet.cs \
	Source/Core/Map/SidedefPart.cs \
	Source/Core/Map/Linedef.cs \
	Source/Core/Map/SplitLineBehavior.cs \
	Source/Core/Map/Sector.cs \
	Source/Core/Map/MapOptions.cs \
	Source/Core/Map/MapElementCollection.cs \
	Source/Core/Map/GroupInfo.cs \
	Source/Core/Map/SectorBuilder.cs \
	Source/Core/Map/MergeGeometryMode.cs \
	Source/Core/Map/BlockEntry.cs \
	Source/Core/Map/BlockMap.cs \
	Source/Core/Map/UniValue.cs \
	Source/Core/Map/ITaggedMapElement.cs \
	Source/Core/Actions/EndActionAttribute.cs \
	Source/Core/Actions/ActionDelegate.cs \
	Source/Core/Actions/MouseInput.cs \
	Source/Core/Actions/SpecialKeys.cs \
	Source/Core/Actions/KeyControl.cs \
	Source/Core/Actions/Action.cs \
	Source/Core/Actions/HintsManager.cs \
	Source/Core/Actions/ActionManager.cs \
	Source/Core/Actions/BeginActionAttribute.cs \
	Source/Core/Actions/ActionAttribute.cs \
	Source/Core/IO/UniversalMapSetIO.cs \
	Source/Core/IO/IMapSetIO.cs \
	Source/Core/IO/DeserializerStream.cs \
	Source/Core/IO/DoomPictureReader.cs \
	Source/Core/IO/UniversalParser.cs \
	Source/Core/IO/UnknownImageReader.cs \
	Source/Core/IO/HexenMapSetIO.cs \
	Source/Core/IO/ClippedStream.cs \
	Source/Core/IO/ClipboardStreamWriter.cs \
	Source/Core/IO/UniversalStreamReader.cs \
	Source/Core/IO/UniversalEntry.cs \
	Source/Core/IO/MapSetIO.cs \
	Source/Core/IO/WAD.cs \
	Source/Core/IO/IReadWriteStream.cs \
	Source/Core/IO/ClipboardStreamReader.cs \
	Source/Core/IO/Lump.cs \
	Source/Core/IO/UniversalStreamWriter.cs \
	Source/Core/IO/Configuration.cs \
	Source/Core/IO/DirectoryFileEntry.cs \
	Source/Core/IO/DirectoryFilesList.cs \
	Source/Core/IO/SerializerStream.cs \
	Source/Core/IO/IImageReader.cs \
	Source/Core/IO/DoomMapSetIO.cs \
	Source/Core/IO/FileImageReader.cs \
	Source/Core/IO/UniversalCollection.cs \
	Source/Core/IO/DoomColormapReader.cs \
	Source/Core/IO/DoomFlatReader.cs \
	Source/Core/Compilers/NodesCompiler.cs \
	Source/Core/Compilers/Compiler.cs \
	Source/Core/Compilers/CompilerError.cs \
	Source/Core/Compilers/AccCompiler.cs \
	Source/Core/VisualModes/VisualVertex.cs \
	Source/Core/VisualModes/VisualCamera.cs \
	Source/Core/VisualModes/VisualBlockEntry.cs \
	Source/Core/VisualModes/VisualBlockMap.cs \
	Source/Core/VisualModes/VisualPickResult.cs \
	Source/Core/VisualModes/VisualSector.cs \
	Source/Core/VisualModes/VisualThing.cs \
	Source/Core/VisualModes/IVisualPickable.cs \
	Source/Core/VisualModes/VisualMode.cs \
	Source/Core/VisualModes/VisualGeometry.cs \
	Source/Core/Types/RandomFloatHandler.cs \
	Source/Core/Types/EnumOptionAndBitsHandler.cs \
	Source/Core/Types/ThingRadiusHandler.cs \
	Source/Core/Types/TypeHandlerAttribute.cs \
	Source/Core/Types/ColorHandler.cs \
	Source/Core/Types/AngleRadiansHandler.cs \
	Source/Core/Types/LinedefTypeHandler.cs \
	Source/Core/Types/AngleDegreesFloatHandler.cs \
	Source/Core/Types/ThingClassHandler.cs \
	Source/Core/Types/ThingTypeHandler.cs \
	Source/Core/Types/NullHandler.cs \
	Source/Core/Types/EnumOptionHandler.cs \
	Source/Core/Types/FlatHandler.cs \
	Source/Core/Types/TextureHandler.cs \
	Source/Core/Types/EnumBitsHandler.cs \
	Source/Core/Types/EnumStringsHandler.cs \
	Source/Core/Types/ThingHeightHandler.cs \
	Source/Core/Types/SectorEffectHandler.cs \
	Source/Core/Types/StringHandler.cs \
	Source/Core/Types/LinedefTagHandler.cs \
	Source/Core/Types/UniversalType.cs \
	Source/Core/Types/TypesManager.cs \
	Source/Core/Types/AngleDegreesHandler.cs \
	Source/Core/Types/BoolHandler.cs \
	Source/Core/Types/SectorTagHandler.cs \
	Source/Core/Types/TypeHandler.cs \
	Source/Core/Types/ThingTagHandler.cs \
	Source/Core/Types/RandomIntegerHandler.cs \
	Source/Core/Types/AngleByteHandler.cs \
	Source/Core/Types/PolyobjectNumberHandler.cs \
	Source/Core/Types/IntegerHandler.cs \
	Source/Core/Types/FloatHandler.cs \
	Source/Core/Data/ImageLoadState.cs \
	Source/Core/Data/FlatImage.cs \
	Source/Core/Data/Scripting/ScriptHandler.cs \
	Source/Core/Data/Scripting/FindUsagesResult.cs \
	Source/Core/Data/Scripting/ModeldefScriptHandler.cs \
	Source/Core/Data/Scripting/AccScriptHandler.cs \
	Source/Core/Data/Scripting/ScriptResource.cs \
	Source/Core/Data/Scripting/ZScriptScriptHandler.cs \
	Source/Core/Data/Scripting/DecorateScriptHandler.cs \
	Source/Core/Data/Scripting/ScriptHandlerAttribute.cs \
	Source/Core/Data/ImageData.cs \
	Source/Core/Data/CameraTextureImage.cs \
	Source/Core/Data/SpriteImage.cs \
	Source/Core/Data/FileImage.cs \
	Source/Core/Data/TextureImage.cs \
	Source/Core/Data/TexturePatch.cs \
	Source/Core/Data/CvarsCollection.cs \
	Source/Core/Data/PK3StructuredReader.cs \
	Source/Core/Data/BitmapImage.cs \
	Source/Core/Data/HiResImage.cs \
	Source/Core/Data/SimpleTextureImage.cs \
	Source/Core/Data/PK3Reader.cs \
	Source/Core/Data/PK3FileImage.cs \
	Source/Core/Data/DataLocation.cs \
	Source/Core/Data/DataReader.cs \
	Source/Core/Data/DirectoryReader.cs \
	Source/Core/Data/Playpal.cs \
	Source/Core/Data/DataLocationList.cs \
	Source/Core/Data/ColormapImage.cs \
	Source/Core/Data/PatchNames.cs \
	Source/Core/Data/ImageDataFormat.cs \
	Source/Core/Data/DataManager.cs \
	Source/Core/Data/TEXTURESImage.cs \
	Source/Core/Data/DynamicBitmapImage.cs \
	Source/Core/Data/UnknownImage.cs \
	Source/Core/Data/WADReader.cs \
	Source/Core/Data/PreviewManager.cs \
	Source/Core/Data/ColorImage.cs \
	Source/Core/Data/VoxelImage.cs \
	Source/Core/Data/ResourceImage.cs \
	Source/Core/ZDoom/Scripting/AcsParserSE.cs \
	Source/Core/ZDoom/Scripting/ScriptTypeParserSE.cs \
	Source/Core/ZDoom/Scripting/DecorateParserSE.cs \
	Source/Core/ZDoom/Scripting/ModeldefParserSE.cs \
	Source/Core/ZDoom/Scripting/ZScriptParserSE.cs \
	Source/Core/ZDoom/CvarInfoParser.cs \
	Source/Core/ZDoom/PatchStructure.cs \
	Source/Core/ZDoom/AnimdefsParser.cs \
	Source/Core/ZDoom/TerrainParser.cs \
	Source/Core/ZDoom/SoundInfo.cs \
	Source/Core/ZDoom/DecorateCategoryInfo.cs \
	Source/Core/ZDoom/ZScriptParser.cs \
	Source/Core/ZDoom/LockDefsParser.cs \
	Source/Core/ZDoom/TexturesParser.cs \
	Source/Core/ZDoom/VoxeldefParser.cs \
	Source/Core/ZDoom/X11R6RGBParser.cs \
	Source/Core/ZDoom/DecorateStateStructure.cs \
	Source/Core/ZDoom/StateStructure.cs \
	Source/Core/ZDoom/DecorateStateGoto.cs \
	Source/Core/ZDoom/DecorateParser.cs \
	Source/Core/ZDoom/AmbientSoundInfo.cs \
	Source/Core/ZDoom/ZScriptActorStructure.cs \
	Source/Core/ZDoom/GldefsParser.cs \
	Source/Core/ZDoom/ZDTextParser.cs \
	Source/Core/ZDoom/ModeldefParser.cs \
	Source/Core/ZDoom/StateGoto.cs \
	Source/Core/ZDoom/ZScriptTokenizer.cs \
	Source/Core/ZDoom/DecorateActorStructure.cs \
	Source/Core/ZDoom/ModeldefStructure.cs \
	Source/Core/ZDoom/ActorStructure.cs \
	Source/Core/ZDoom/MapinfoParser.cs \
	Source/Core/ZDoom/SndInfoParser.cs \
	Source/Core/ZDoom/ZScriptStateGoto.cs \
	Source/Core/ZDoom/ZScriptStateStructure.cs \
	Source/Core/ZDoom/TextureStructure.cs \
	Source/Core/ZDoom/SndSeqParser.cs \
	Source/Core/ZDoom/ReverbsParser.cs \
	Source/Core/Config/AllTexturesSet.cs \
	Source/Core/Config/MapLumpInfo.cs \
	Source/Core/Config/GeneralizedBit.cs \
	Source/Core/Config/SkillInfo.cs \
	Source/Core/Config/TextureSet.cs \
	Source/Core/Config/GeneralizedOption.cs \
	Source/Core/Config/ArgumentInfo.cs \
	Source/Core/Config/NodebuilderInfo.cs \
	Source/Core/Config/EnumList.cs \
	Source/Core/Config/CompilerInfo.cs \
	Source/Core/Config/UniversalFieldInfo.cs \
	Source/Core/Config/EnumItem.cs \
	Source/Core/Config/DefinedTextureSet.cs \
	Source/Core/Config/ConfigurationInfo.cs \
	Source/Core/Config/GameConfiguration.cs \
	Source/Core/Config/ResourceTextureSet.cs \
	Source/Core/Config/LinedefActivateInfo.cs \
	Source/Core/Config/ThingTypeInfo.cs \
	Source/Core/Config/SectorEffectInfo.cs \
	Source/Core/Config/GameType.cs \
	Source/Core/Config/LinedefActionCategory.cs \
	Source/Core/Config/IFilledTextureSet.cs \
	Source/Core/Config/SectorEffectData.cs \
	Source/Core/Config/PasteOptions.cs \
	Source/Core/Config/MatchingTextureSet.cs \
	Source/Core/Config/LinedefActionInfo.cs \
	Source/Core/Config/ThingsFlagsCompare.cs \
	Source/Core/Config/TagType.cs \
	Source/Core/Config/ThingCategory.cs \
	Source/Core/Config/ScriptDocumentSettings.cs \
	Source/Core/Config/INumberedTitle.cs \
	Source/Core/Config/ProgramConfiguration.cs \
	Source/Core/Config/FlagTranslation.cs \
	Source/Core/Config/GeneralizedCategory.cs \
	Source/Core/Config/ScriptConfiguration.cs \
	Source/Core/Windows/ScriptGoToLineForm.Designer.cs \
	Source/Core/Windows/CenterOnCoordinatesForm.cs \
	Source/Core/Windows/FlagsForm.cs \
	Source/Core/Windows/FindReplaceOptions.cs \
	Source/Core/Windows/ThingEditForm.Designer.cs \
	Source/Core/Windows/ConfigForm.Designer.cs \
	Source/Core/Windows/LinedefEditFormUDMF.cs \
	Source/Core/Windows/ThingBrowserForm.cs \
	Source/Core/Windows/AngleForm.cs \
	Source/Core/Windows/StatusInfo.cs \
	Source/Core/Windows/ToolbarSection.cs \
	Source/Core/Windows/CenterOnCoordinatesForm.Designer.cs \
	Source/Core/Windows/BitFlagsForm.cs \
	Source/Core/Windows/ErrorsForm.Designer.cs \
	Source/Core/Windows/PreferencesController.cs \
	Source/Core/Windows/UpdateForm.Designer.cs \
	Source/Core/Windows/ThingEditFormUDMF.cs \
	Source/Core/Windows/SectorEditFormUDMF.Designer.cs \
	Source/Core/Windows/ActionBrowserForm.cs \
	Source/Core/Windows/OpenMapOptionsForm.Designer.cs \
	Source/Core/Windows/MenuSection.cs \
	Source/Core/Windows/ScriptEditorForm.cs \
	Source/Core/Windows/PasteOptionsForm.Designer.cs \
	Source/Core/Windows/ChangeMapForm.Designer.cs \
	Source/Core/Windows/PasteOptionsForm.cs \
	Source/Core/Windows/ChangeMapForm.cs \
	Source/Core/Windows/PreferencesForm.Designer.cs \
	Source/Core/Windows/IMainForm.cs \
	Source/Core/Windows/TanColorTable.cs \
	Source/Core/Windows/AngleForm.Designer.cs \
	Source/Core/Windows/TagStatisticsForm.cs \
	Source/Core/Windows/ExceptionDialog.designer.cs \
	Source/Core/Windows/ConfigForm.cs \
	Source/Core/Windows/SectorEditForm.Designer.cs \
	Source/Core/Windows/MessageBeepType.cs \
	Source/Core/Windows/CustomFieldsForm.Designer.cs \
	Source/Core/Windows/TextureBrowserForm.Designer.cs \
	Source/Core/Windows/LinedefColorPresetsForm.cs \
	Source/Core/Windows/GridSetupForm.cs \
	Source/Core/Windows/ResourceOptionsForm.cs \
	Source/Core/Windows/ActionBrowserForm.Designer.cs \
	Source/Core/Windows/ThingsFiltersForm.Designer.cs \
	Source/Core/Windows/MapOptionsForm.Designer.cs \
	Source/Core/Windows/VertexEditForm.cs \
	Source/Core/Windows/ScriptEditorForm.Designer.cs \
	Source/Core/Windows/CustomFieldsForm.cs \
	Source/Core/Windows/AboutForm.cs \
	Source/Core/Windows/ThingStatisticsForm.Designer.cs \
	Source/Core/Windows/SectorEditFormUDMF.cs \
	Source/Core/Windows/ThingEditFormUDMF.Designer.cs \
	Source/Core/Windows/FlagsForm.Designer.cs \
	Source/Core/Windows/ResourceOptionsForm.Designer.cs \
	Source/Core/Windows/TextEditForm.Designer.cs \
	Source/Core/Windows/BitFlagsAndOptionsForm.cs \
	Source/Core/Windows/ThingsFiltersForm.cs \
	Source/Core/Windows/MapOptionsForm.cs \
	Source/Core/Windows/MainForm.Designer.cs \
	Source/Core/Windows/PluginToolbarButton.cs \
	Source/Core/Windows/TagStatisticsForm.Designer.cs \
	Source/Core/Windows/LinedefColorPresetsForm.Designer.cs \
	Source/Core/Windows/ScriptFindReplaceForm.cs \
	Source/Core/Windows/OpenMapOptionsForm.cs \
	Source/Core/Windows/TextEditForm.cs \
	Source/Core/Windows/TextureSetForm.cs \
	Source/Core/Windows/LinedefEditForm.Designer.cs \
	Source/Core/Windows/LinedefEditFormUDMF.Designer.cs \
	Source/Core/Windows/LinedefEditForm.cs \
	Source/Core/Windows/BitFlagsForm.Designer.cs \
	Source/Core/Windows/ThingEditForm.cs \
	Source/Core/Windows/ErrorsForm.cs \
	Source/Core/Windows/ThingBrowserForm.Designer.cs \
	Source/Core/Windows/EffectBrowserForm.cs \
	Source/Core/Windows/ScriptFindReplaceForm.Designer.cs \
	Source/Core/Windows/ScriptGoToLineForm.cs \
	Source/Core/Windows/ExceptionDialog.cs \
	Source/Core/Windows/MainForm.cs \
	Source/Core/Windows/PreferencesForm.cs \
	Source/Core/Windows/TextureSetForm.Designer.cs \
	Source/Core/Windows/DelayedForm.cs \
	Source/Core/Windows/TextureBrowserForm.cs \
	Source/Core/Windows/VertexEditForm.Designer.cs \
	Source/Core/Windows/ThingStatisticsForm.cs \
	Source/Core/Windows/SectorEditForm.cs \
	Source/Core/Windows/EffectBrowserForm.Designer.cs \
	Source/Core/Windows/AboutForm.Designer.cs \
	Source/Core/Windows/UpdateForm.cs \
	Source/Core/Windows/BitFlagsAndOptionsForm.Designer.cs \
	Source/Core/Windows/GridSetupForm.Designer.cs \
	Source/Core/Rendering/Color3.cs \
	Source/Core/Rendering/Color4.cs \
	Source/Core/Rendering/Vector2.cs \
	Source/Core/Rendering/Vector3.cs \
	Source/Core/Rendering/Vector4.cs \
	Source/Core/Rendering/Matrix.cs \
	Source/Core/Rendering/IRenderResource.cs \
	Source/Core/Rendering/RenderDevice.cs \
	Source/Core/Rendering/Texture.cs \
	Source/Core/Rendering/VertexBuffer.cs \
	Source/Core/Rendering/IndexBuffer.cs \
	Source/Core/Rendering/Mesh.cs \
	Source/Core/Rendering/SurfaceBufferSet.cs \
	Source/Core/Rendering/TextAlignment.cs \
	Source/Core/Rendering/PixelColor.cs \
	Source/Core/Rendering/CustomTextLabel.cs \
	Source/Core/Rendering/TextFont.cs \
	Source/Core/Rendering/WorldVertex.cs \
	Source/Core/Rendering/FlatQuad.cs \
	Source/Core/Rendering/Renderer2D.cs \
	Source/Core/Rendering/TextLabel.cs \
	Source/Core/Rendering/ColorSetting.cs \
	Source/Core/Rendering/ViewMode.cs \
	Source/Core/Rendering/Renderer3D.cs \
	Source/Core/Rendering/RenderPasses.cs \
	Source/Core/Rendering/RenderLayers.cs \
	Source/Core/Rendering/SurfaceManager.cs \
	Source/Core/Rendering/IRenderer2D.cs \
	Source/Core/Rendering/SurfaceEntryCollection.cs \
	Source/Core/Rendering/Plotter.cs \
	Source/Core/Rendering/RenderModeEnums.cs \
	Source/Core/Rendering/IRenderer3D.cs \
	Source/Core/Rendering/Presentation.cs \
	Source/Core/Rendering/VisualVertexHandle.cs \
	Source/Core/Rendering/ColorCollection.cs \
	Source/Core/Rendering/FlatVertex.cs \
	Source/Core/Rendering/SurfaceUpdate.cs \
	Source/Core/Rendering/Renderer.cs \
	Source/Core/Rendering/SurfaceEntry.cs \
	Source/Core/Rendering/CommentType.cs \
	Source/Core/General/Launcher.cs \
	Source/Core/General/FileLockChecker.cs \
	Source/Core/General/MapManager.cs \
	Source/Core/General/ErrorItem.cs \
	Source/Core/General/General.cs \
	Source/Core/General/Clock.cs \
	Source/Core/General/SavePurpose.cs \
	Source/Core/General/UpdateChecker.cs \
	Source/Core/General/MD5Hash.cs \
	Source/Core/General/MurmurHash2.cs \
	Source/Core/General/CRC.cs \
	Source/Core/General/AssemblyHash.cs \
	Source/Core/General/StepsList.cs \
	Source/Core/General/BinaryHeap.cs \
	Source/Core/General/ErrorLogger.cs

core_defines = \
	-define:NO_SCINTILLA \
	-define:NO_FORMS_DESIGN

core_references = \
	-r:System.Windows.Forms.dll \
	-r:System.Drawing.dll \
	-r:System.Data.dll \
	-r:System.Management.dll \
	-r:Build/SharpCompress.dll

core: $(Core)
	@echo Compiling gzdb..
	@mono-csc -unsafe -target:exe -out:Build/Builder.exe $(core_defines) $(core_references) $(Core)

all: core
